# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDailyDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOQ', models.DecimalField(decimal_places=2, max_digits=5, max_length=5, null=True, verbose_name='\u5f00\u76d8\u4ef7')),
                ('SCQ', models.DecimalField(decimal_places=2, max_digits=5, max_length=5, null=True, verbose_name='\u6536\u76d8\u4ef7')),
            ],
            options={
                'verbose_name': '\u80a1\u7968\u8be6\u7ec6\u6570\u636e',
                'verbose_name_plural': '\u80a1\u7968\u8be6\u7ec6\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='ShareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u540d\u79f0')),
                ('types', models.CharField(choices=[('H', 'SH'), ('S', 'SZ')], default='SH', max_length=5, verbose_name='\u7c7b\u578b')),
                ('code', models.PositiveIntegerField(verbose_name='\u7f16\u53f7')),
            ],
            options={
                'verbose_name': '\u80a1\u7968',
                'verbose_name_plural': '\u80a1\u7968',
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('sex', models.CharField(choices=[('G', '\u5973'), ('B', '\u7537')], default='B', max_length=4, verbose_name='\u6027\u522b')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('cellphones', models.CharField(max_length=11, verbose_name='\u624b\u673a')),
                ('image', models.FileField(upload_to=b'', verbose_name='\u56fe\u50cf')),
                ('address', models.CharField(max_length=100, verbose_name='\u5bb6\u5ead\u4f4f\u5740')),
                ('birthday', models.DateField(verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('profession', models.CharField(max_length=30, verbose_name='\u804c\u4e1a')),
                ('rvenue', models.IntegerField(verbose_name='\u5e74\u6536\u5165(\u4e07)')),
                ('province', models.CharField(choices=[('000006', '\u6d59\u6c5f'), ('000012', '\u56db\u5ddd'), ('000009', '\u6e56\u5317'), ('000013', '\u8d35\u5dde'), ('000005', '\u5929\u6d25'), ('000010', '\u798f\u5efa'), ('000007', '\u5929\u6d25'), ('000001', '\u5317\u4eac'), ('000004', '\u91cd\u5e86'), ('000003', '\u5e7f\u4e1c'), ('000008', '\u6e56\u5357'), ('000002', '\u4e0a\u6d77'), ('000011', '\u6c5f\u897f')], max_length=10, verbose_name='\u7701\u4efd')),
                ('blog', models.URLField(max_length=50, null=True, verbose_name='\u7f51\u5740')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('alisa', models.CharField(max_length=50, verbose_name='\u6635\u79f0')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='sharedailydetailmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ShareModel', verbose_name='\u540d\u79f0'),
        ),
    ]
