# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4e66\u540d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u4ef7\u683c')),
                ('profile', models.CharField(max_length=200, verbose_name='\u7b80\u4ecb')),
                ('publisher_date', models.DateField(auto_now_add=True, verbose_name='\u51fa\u7248\u65e5\u671f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UsersModel', verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u51fa\u7248\u793e',
                'verbose_name_plural': '\u51fa\u7248\u793e',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u51fa\u7248\u793e')),
                ('rank', models.CharField(choices=[('004', '\u56db\u661f'), ('003', '\u4e09\u661f'), ('005', '\u4e94\u661f'), ('002', '\u4e8c\u661f'), ('001', '\u4e00\u661f')], max_length=2, verbose_name='\u51fa\u7248\u793e\u7b49\u7ea7')),
                ('address', models.CharField(max_length=200, verbose_name='\u51fa\u7248\u793e\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u51fa\u7248\u793e',
                'verbose_name_plural': '\u51fa\u7248\u793e',
            },
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Publisher', verbose_name='\u51fa\u7248\u793e'),
        ),
    ]
