# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170930_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': '\u4e66', 'verbose_name_plural': '\u4e66'},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='rank',
            field=models.CharField(choices=[('004', '\u56db\u661f'), ('003', '\u4e09\u661f'), ('005', '\u4e94\u661f'), ('002', '\u4e8c\u661f'), ('001', '\u4e00\u661f')], max_length=3, verbose_name='\u51fa\u7248\u793e\u7b49\u7ea7'),
        ),
    ]
