# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170930_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='rank',
            field=models.CharField(choices=[('\u2605\u2605', '\u4e8c\u661f'), ('\u2605\u2605\u2605', '\u4e09\u661f'), ('\u2605\u2605\u2605\u2605\u2605', '\u4e94\u661f'), ('\u2605', '\u4e00\u661f'), ('\u2605\u2605\u2605\u2605', '\u56db\u661f')], max_length=10, verbose_name='\u51fa\u7248\u793e\u7b49\u7ea7'),
        ),
    ]
